name: Deploy Release

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_SUBSCRIPTION:
        required: true
      AZURE_RG:
        required: true
      BLOB_STORAGE_ENDPOINT:
        required: true
      DATA_LAKE_STORAGE_URL:
        required: true
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@main
      with:
        ref: 'adf_publish'

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./dev-covid-demo-adf/ARMTemplateForFactory.json
        parameters: factoryName=${{ vars.FACTORY_NAME }} ls_blob_coviddemostrgacct_properties_typeProperties_serviceEndpoint=${{secrets.BLOB_STORAGE_ENDPOINT}} ls_datalake_coviddemodl_properties_typeProperties_url=${{secrets.DATA_LAKE_STORAGE_URL}}
